// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'room': string;
  'roomInfo': string;
  'roomMessagePreview': string;
  'roomName': string;
  'roomPhoto': string;
}
export const cssExports: CssExports;
export default cssExports;
