// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'notification': string;
  'notification__avatar': string;
  'notification__body__from': string;
}
export const cssExports: CssExports;
export default cssExports;
