// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'userInfo': string;
  'userName': string;
  'userPhoto': string;
  'userSettings': string;
}
export const cssExports: CssExports;
export default cssExports;
