// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Registration': string;
  'backText': string;
  'backToLogin': string;
  'error': string;
  'forwardText': string;
  'loginText': string;
  'signUpButton': string;
}
export const cssExports: CssExports;
export default cssExports;
