// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chatContent': string;
  'mainWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
