// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chatMessage': string;
  'messageBody': string;
  'messageSender': string;
  'messageSenderUsername': string;
  'messageStatus': string;
  'messageTime': string;
  'messageWrapper': string;
  'ownMessage': string;
  'uploadImage': string;
}
export const cssExports: CssExports;
export default cssExports;
