// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backText': string;
  'error': string;
  'forgotPassword': string;
  'forwardText': string;
  'loginButtons': string;
  'loginFormContent': string;
  'loginMenu': string;
  'loginNowButton': string;
  'loginText': string;
  'partLoginForm': string;
  'passwordAndEmailText': string;
  'registrationButton': string;
  'signInWithGoogle': string;
  'wrapperLoginForm': string;
}
export const cssExports: CssExports;
export default cssExports;
