// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contact': string;
  'contactInfo': string;
  'contactInfoPhoto': string;
  'selectedContact': string;
}
export const cssExports: CssExports;
export default cssExports;
