// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'exitAction': string;
  'imagesListItem': string;
  'imagesListItem_active': string;
  'imagesListWrapper': string;
  'imagesSliderWrapper': string;
  'imgBlock': string;
  'mainImg': string;
}
export const cssExports: CssExports;
export default cssExports;
