// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appSettings': string;
  'appSettingsContainer': string;
  'appSettingsNav': string;
  'appSettingsNavItem': string;
}
export const cssExports: CssExports;
export default cssExports;
