// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionImg': string;
  'actionImgWrapper': string;
  'createGroupBtn': string;
  'createGroupContacts': string;
  'createGroupForm': string;
  'createGroupWrapper': string;
  'profileImg': string;
  'wrapperGroupImg': string;
}
export const cssExports: CssExports;
export default cssExports;
