// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chatSendMessage': string;
  'emojiPickerButton': string;
  'photoAction': string;
  'sendMessageButton': string;
}
export const cssExports: CssExports;
export default cssExports;
