// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerSettings': string;
  'headerSettingsPopoverItem': string;
}
export const cssExports: CssExports;
export default cssExports;
