// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionImg': string;
  'actionImgWrapper': string;
  'bio': string;
  'btnShown': string;
  'error': string;
  'profileImg': string;
  'userFormWrapper': string;
  'username': string;
  'wrapperProfileImg': string;
}
export const cssExports: CssExports;
export default cssExports;
