// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chatSettings': string;
  'header': string;
  'headerChatInfo': string;
  'headerGroupInfo': string;
  'headerGroupInfoMembers': string;
  'headerGroupInfoOverlay': string;
  'headerGroupInfo__show': string;
  'room': string;
  'roomInfo': string;
  'roomName': string;
  'roomPhoto': string;
  'roomStatus': string;
}
export const cssExports: CssExports;
export default cssExports;
